#pragma once

#include <stdint.h>

#include "packet_format.h"
#include "server_control.h"


// Event types
enum EVENT_TYPES{
    EVENT_NULL = 0,
    // Is called by a threaded environment
    PACKET,
    CLIENT_SOCKET_HAS_DISCONNECTED,

    // Single threaded environment
    SERVER_IS_SHUTTING_DOWN,
    SERVER_STARTING,

    //plans for it are there, but actual dispatching and recovery is not yet implemented
    // Two levels of recovery:
    // Server internals tries to recover the parameters it had
    // Server dispatches event for handlers to recover their state
    SERVER_STARTING_TRY_RECOVER
};

struct event{
    enum EVENT_TYPES type;
    struct packet *packet;
    uint16_t generated_by;
    struct server_context *server;

    //When event is generated by the same client, it keeps the previous value it had at the end of the previous call
    void *client_persistent_data;
};

void event_init(struct event *event);
void event_destroy(struct event *event);


